### PR TITLE
Update Postgres to 13.8 and backport bc7a40b4 to fix new Xcode build

### LINKED ISSUE #263: Unable to build with macOS SDK 13.0
XCode 14.1, which was released yesterday, now ships with macOS SDK 13.0.

`pg_query` does not build at the moment. This is the output of a `bundle exec rake compile`:

<details>
<pre>
In file included from gram.y:46:
In file included from /Users/stanhu/github/pg_query/ext/pg_query/include/postgres.h:46:
In file included from /Users/stanhu/github/pg_query/ext/pg_query/include/c.h:1330:
In file included from /Users/stanhu/github/pg_query/ext/pg_query/include/port.h:17:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netdb.h:91:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/netinet/in.h:81:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/socket.h:425:1: error: expected ';' after top level declarator
__CCT_DECLARE_CONSTRAINED_PTR_TYPES(struct sockaddr, sockaddr);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:587:101: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPES'
#define __CCT_DECLARE_CONSTRAINED_PTR_TYPES(basetype, basetag)                                      \
                                                                                                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:580:2: note: expanded from macro '\
__CCT_DECLARE_CONSTRAINED_PTR_TYPE'
        __CCT_DISPATCH(__CCT_DECLARE_CONSTRAINED_PTR_TYPE, basetype, basetag, __VA_ARGS__)
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:548:2: note: expanded from macro '__CCT_DISPATCH'
        __CCT_DISPATCH1(base, __CCT_COUNT_ARGS(__VA_ARGS__), __VA_ARGS__)
        ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:113:26: note: expanded from macro '__CONCAT'
#define __CONCAT(x, y)   x ## y
                         ^
<scratch space>:415:1: note: expanded from here
__CCT_DECLARE_CONSTRAINED_PTR_TYPE_3
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/constrained_ctypes.h:563:14: note: expanded from macro '__CCT_DECLARE_CONSTRAINED_PTR_TYPE_3'
        __CCT_DEFER(__CONCAT, basetag,  __CCT_CONTRACT_LIST_TO_TAGGED_SUFFIX_1(kind))
                    ^
</pre>
</details>

[pg_query-rake-compile.txt](https://github.com/pganalyze/pg_query/files/9924075/pg_query-rake-compile.txt)

Downgrading to macOS SDK 12.3 appears to solve the problem:

```shell
sudo mkdir /Library/Developer/CommandLineTools/SDKs/backup
sudo mv /Library/Developer/CommandLineTools/SDKs/MacOSX13* /Library/Developer/CommandLineTools/SDKs/backup
```

I'm not yet sure what's going on here because this test program works fine:

```c
#include <ctype.h>
#include <netdb.h>
#include <pwd.h>

int main()
{
}
```

### PR DESCRIPTION
**Pull request by lfittl**
See https://postgr.es/m/1803927.1665938411@sss.pgh.pa.us for discussion of the Xcode build issue. Fixed in bc7a40b4, which is on REL_13_STABLE but not yet in an official Postgres release.

In passing this also fixes an extract source script issue with newer clang versions.

Fixes https://github.com/pganalyze/pg_query/issues/263

### CODE REVIEW

File: scripts/extract_source.rb [hunk 1]
```diff
@@ -253,10 +262,15 @@ def analyze_file(file)
             analysis.file_to_symbol_positions[cursor.location.file][cursor.spelling] = [start_offset, end_offset]
 
             cursor.visit_children do |child_cursor, parent|
+              # There seems to be a bug here on modern Clang versions where the
+              # cursor kind gets modified once we call "child_cursor.definition"
+              # - thus we make a copy ahead of calling that, for later use
+              child_cursor_kind = child_cursor.kind
```
Comment (msakrejda) [inline scripts/extract_source.rb:268]: Oof. Is this worth reporting?

**Review by msakrejda — APPROVED** [review]

File: scripts/extract_source.rb (hunk 1 above)
Comment (lfittl) [reply scripts/extract_source.rb:268]: Maybe? I think the issue here is likely in the Ruby binding, which is semi-maintained.

Its a bit of a time sink to reproduce this, so I'll punt on this for now.
